language: python
python:
  - "3.6"
# Do not move from the root dir. requirements.txt is here
before_install:
  - wget https://chromedriver.storage.googleapis.com/2.34/chromedriver_linux64.zip
  - sudo unzip chromedriver_linux64.zip -d /usr/bin
  - apt-get install xvfb
script:
  - pytest --cov=surebet surebet/tests
after_success:
  - bash <(curl -s https://codecov.io/bash) -t 98c1d7ba-04ce-4fd7-b487-9e8938227ef6