sudo: false
git:
  depth: 15
cache:
  pip: true
  directories:
  - $HOME/Downloads
 
language: python
python:
  - "3.6"
# Do not move from the root dir. requirements.txt is here
addons:
  chrome: stable
  apt:
    packages:
      - xvfb
before_install:
  - wget https://chromedriver.storage.googleapis.com/2.35/chromedriver_linux64.zip -O temp.zip; unzip temp.zip -o -d $HOME/Downloads; rm temp.zip
  - export PATH="$HOME/Downloads/chromedriver:$PATH"
script:
  - pytest --cov=surebet surebet/tests
after_success:
  - bash <(curl -s https://codecov.io/bash) -t 98c1d7ba-04ce-4fd7-b487-9e8938227ef6
